[phases.setup]
# System dependencies for Chrome/Chromium and web scraping
# Updated for Ubuntu 24.04 (Noble) - some packages renamed with t64 suffix
aptPkgs = [
    "chromium-browser",
    "chromium-chromedriver",
    "wget",
    "curl",
    "ca-certificates",
    "fonts-liberation",
    "libasound2t64",
    "libatk-bridge2.0-0t64",
    "libatk1.0-0t64",
    "libcairo2",
    "libcups2t64",
    "libdbus-1-3",
    "libdrm2",
    "libgbm1",
    "libgtk-3-0t64",
    "libnspr4",
    "libnss3",
    "libpango-1.0-0",
    "libx11-6",
    "libxcb1",
    "libxcomposite1",
    "libxdamage1",
    "libxext6",
    "libxfixes3",
    "libxkbcommon0",
    "libxrandr2"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[start]
# Handle PORT dynamically in Python (Railway standard)
cmd = "python -c \"import os; from web_app import app; app.run(debug=False, host='0.0.0.0', port=int(os.environ.get('PORT', 5000)))\""
