[phases.setup]
# System dependencies for Chrome/Chromium and web scraping
aptPkgs = [
    "chromium-browser",
    "chromium-chromedriver",
    "wget",
    "curl",
    "ca-certificates",
    "fonts-liberation",
    "libappindicator3-1",
    "libasound2",
    "libatk-bridge2.0-0",
    "libatk1.0-0",
    "libc6",
    "libcairo2",
    "libcups2",
    "libdbus-1-3",
    "libexpat1",
    "libfontconfig1",
    "libgbm1",
    "libgcc1",
    "libglib2.0-0",
    "libgtk-3-0",
    "libnspr4",
    "libnss3",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libstdc++6",
    "libx11-6",
    "libx11-xcb1",
    "libxcb1",
    "libxcomposite1",
    "libxcursor1",
    "libxdamage1",
    "libxext6",
    "libxfixes3",
    "libxi6",
    "libxrandr2",
    "libxrender1",
    "libxss1",
    "libxtst6",
    "lsb-release",
    "xdg-utils"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[start]
# Handle PORT dynamically in Python (Railway standard)
cmd = "python -c \"import os; from web_app import app; app.run(debug=False, host='0.0.0.0', port=int(os.environ.get('PORT', 5000)))\""
